/*
 * Copyright (c) 2013. CMG Ltd All rights reserved.
 *
 * This software is the confidential and proprietary information of CMG
 * ("Confidential Information"). You shall not disclose such Confidential
 * Information and shall use it only in accordance with the terms of the
 * license agreement you entered into with CMG.
 */

package com.cmg.android.common;

/**
 * This class was generated by Maven build
 * DO NOT CHANGE ON JAVA SOURCE
 * Check src/templates/java folder
 *
 * @author $Author$
 * @version $Revision$
 * @Creator Hai Lu
 * @Last changed: $LastChangedDate$
 */

public class Constant {
    public static final String SENDER_ID = "371638778910";
}